server:
  port: 8203

mybatis-plus:
  type-enums-package: com.molloi.ssyx.enums
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

spring:
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://47.101.204.13:3306/shequ-product?characterEncoding=utf-8&useSSL=false
    username: root
    password: 123456
    hikari:
      maximum-pool-size: 10

  rabbitmq:
    host: 47.101.204.13
    port: 5672
    username: admin
    password: admin
    publisher-confirm-type: CORRELATED  #发布确认模式，消息是否被成功发送到交换机
    publisher-returns: true
    listener:
      simple:
        prefetch: 1
        concurrency: 3
        acknowledge-mode: manual   #消费端手动确认
  servlet:
    multipart:
      max-file-size: 200MB
      max-request-size: 200MB
minio:
  endpoint: http://47.101.204.13:9000
  accessKey: fDDV5UPtUprHLPgPhyAF
  secretKey: jtDMfAxSCunY30acK6ePsam6DmUUnDRb7vvxTJlw
  bucketName: ssyx



  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8

#设置feign客户端超时时间(OpenFeign默认支持ribbon)
ribbon:
  #指的是建立连接所用的时间，适用于网络状况正常的情况下,两端连接所用的时间
  ReadTimeout: 5000
  #指的是建立连接后从服务器读取到可用资源所用的时间
  ConnectTimeout: 5000